name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ./TSEconomy/TSEconomy.csproj

    - name: Build
      run: dotnet build ./TSEconomy/TSEconomy.csproj --no-restore

    - name: Organize Artifacts
      run: |
        mkdir -p ./TSEconomyBuild/ServerPlugins
        mkdir -p ./TSEconomyBuild/bin
        mv ./TSEconomy/bin/Debug/net6.0/* ./TSEconomyBuild/ServerPlugins/
        mv ./deps/* ./TSEconomyBuild/bin/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: TSEconomyBuild
        path: ./TSEconomyBuild/
